CREATE SEQUENCE CONTATO_SEQ INCREMENT BY 1 START 1 MINVALUE 1;

CREATE TABLE contato (
id INTEGER PRIMARY KEY NOT NULL DEFAULT ('CONTATO_SEQ'::regclass),
nome VARCHAR(150) NOT NULL,
telefone VARCHAR(50),
email VARCHAR(150)
);